import { randomUUID } from 'node:crypto';
import { test, expect } from '@playwright/test';

test('private profile editing persists and conflicting saves preserve the draft', async ({ page, context }) => {
  await page.goto('/profile');
  await expect(page).toHaveURL(/\/login$/);
  await page.goto('/register');
  await page.getByLabel('Your name').fill('Profile Tester');
  await page.getByLabel('Email', { exact: true }).fill(`e2e-${randomUUID()}@example.com`);
  await page.getByLabel('Password', { exact: true }).fill('a profile browser passphrase');
  await page.getByRole('button', { name: 'Create account', exact: true }).click();
  await page.getByRole('link', { name: 'View career profile' }).click();
  await expect(page.getByRole('heading', { name: 'Profile Tester', exact: true })).toBeVisible();
  await expect(page.getByText('Your profile is ready to build.', { exact: false })).toBeVisible();
  await page.getByRole('link', { name: 'Edit profile', exact: true }).click();
  await expect(page.getByLabel('Full name', { exact: true })).toHaveValue('Profile Tester');
  await page.getByLabel('Headline').fill('Software engineer');
  await page.getByLabel('Professional summary').fill('Building useful software.');
  await page.getByLabel('Your skills').fill('TypeScript, MongoDB');
  await page.getByRole('button', { name: 'Add experience', exact: true }).click();
  const job = page.getByRole('group', { name: 'Experience 1', exact: true });
  await job.getByLabel('Company').fill('Example');
  await job.getByLabel('Role', { exact: true }).fill('Engineer');
  await job.getByLabel('Start date').fill('2023-01');
  await job.getByLabel('I currently work here').check();
  await expect(job.getByLabel('End date')).toBeDisabled();
  await page.getByRole('button', { name: 'Add education', exact: true }).click();
  const education = page.getByRole('group', { name: 'Education 1', exact: true });
  await education.getByLabel('Institution').fill('Example University');
  await education.getByLabel('Qualification').fill('BSc');
  await education.getByLabel('Start date').fill('2019-08');
  await page.getByRole('button', { name: 'Add certification', exact: true }).click();
  await page.getByLabel('Certification name').fill('Cloud fundamentals');
  await page.getByLabel('Preferred roles').fill('Backend engineer');
  await page.getByLabel('Remote', { exact: true }).check();
  await page.getByLabel('Minimum salary').fill('100000');
  await page.getByLabel('Currency').fill('USD');
  await page.getByRole('button', { name: 'Add professional link', exact: true }).click();
  await page.getByLabel('Link label').fill('GitHub');
  await page.getByLabel('Profile URL').fill('https://github.com/example');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Profile saved.');
  await page.reload();
  await expect(page.getByLabel('Headline')).toHaveValue('Software engineer');
  await expect(page.getByLabel('Your skills')).toHaveValue('TypeScript, MongoDB');
  await expect(job.getByLabel('Company')).toHaveValue('Example');
  await expect(education.getByLabel('Institution')).toHaveValue('Example University');
  await expect(page.getByLabel('Certification name')).toHaveValue('Cloud fundamentals');
  await expect(page.getByLabel('Remote', { exact: true })).toBeChecked();
  await expect(page.getByLabel('Minimum salary')).toHaveValue('100000');
  await expect(page.getByLabel('Profile URL')).toHaveValue('https://github.com/example');

  const second = await context.newPage();
  await second.goto('/profile/edit');
  await expect(second.getByLabel('Headline')).toHaveValue('Software engineer');
  await page.getByLabel('Headline').fill('Senior engineer');
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Profile saved.');
  await second.getByLabel('Headline').fill('My unsaved draft');
  await second.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(second.getByRole('alert')).toContainText('changed in another tab');
  await expect(second.getByLabel('Headline')).toHaveValue('My unsaved draft');
  await expect(second.getByRole('button', { name: 'Save profile', exact: true })).toBeDisabled();
  second.once('dialog', dialog => dialog.accept());
  await second.getByRole('button', { name: 'Reload saved profile' }).click();
  await expect(second.getByLabel('Headline')).toHaveValue('Senior engineer');
  await second.close();

  await page.getByLabel('Headline').fill('');
  await page.getByRole('button', { name: 'Remove professional link 1' }).click();
  await page.getByRole('button', { name: 'Save profile', exact: true }).click();
  await expect(page.getByRole('status')).toHaveText('Profile saved.');
  await page.reload();
  await expect(page.getByLabel('Headline')).toHaveValue('');
  await expect(page.getByLabel('Profile URL')).toHaveCount(0);
  await page.getByRole('link', { name: 'View profile', exact: false }).click();
  await expect(page).toHaveURL(/\/profile$/);
  await expect(page.getByRole('heading', { name: 'Profile Tester', exact: true })).toBeVisible();
  await expect(page.getByText('Building useful software.', { exact: true })).toBeVisible();
  await expect(page.getByText('TypeScript', { exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Engineer', exact: true })).toBeVisible();
  await expect(page.getByText('Jan 2023 – Present')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Example University' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Cloud fundamentals' })).toBeVisible();
  await expect(page.getByText('From 100,000 USD / year', { exact: true })).toBeVisible();
  await expect(page.getByText('No professional links added yet.')).toBeVisible();
  await expect(page.getByRole('textbox')).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.getByRole('link', { name: 'Dashboard', exact: false }).click();
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page).toHaveURL(/\/login$/);
});
